import { ROLES, PERMISSIONS } from '../constants/index.js';

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: ['*'], // Full access
  
  [ROLES.ADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_VERIFY,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.USER_MANAGE_ROLES,
    PERMISSIONS.CAR_VIEW_ALL,
    PERMISSIONS.CAR_APPROVE,
    PERMISSIONS.CAR_REJECT,
    PERMISSIONS.CAR_DELETE,
    PERMISSIONS.BOOKING_VIEW_ALL,
    PERMISSIONS.BOOKING_MANAGE,
    PERMISSIONS.REVIEW_DELETE,
    PERMISSIONS.AUDIT_VIEW,
  ],
  
  [ROLES.MODERATOR]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.CAR_VIEW_ALL,
    PERMISSIONS.CAR_APPROVE,
    PERMISSIONS.CAR_REJECT,
    PERMISSIONS.REVIEW_DELETE,
  ],
  
  [ROLES.SUPPORT]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.BOOKING_VIEW_ALL,
    PERMISSIONS.BOOKING_MANAGE,
  ],
  
  [ROLES.OWNER]: [
    // Standard owner permissions are handled via ownership logic in services
  ],
  
  [ROLES.USER]: [
    // Standard user permissions
  ]
};
